/*
 * This file is generated by jOOQ.
 */
package com.autotesting.db.tables.records;


import com.autotesting.db.tables.TBLAccount;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AccountRecord extends UpdatableRecordImpl<AccountRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>test_db.account.account_id</code>.
     */
    public void setAccountId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>test_db.account.account_id</code>.
     */
    public String getAccountId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>test_db.account.username</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>test_db.account.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>test_db.account.balance</code>.
     */
    public void setBalance(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>test_db.account.balance</code>.
     */
    public Double getBalance() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>test_db.account.profit_loss</code>.
     */
    public void setProfitLoss(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>test_db.account.profit_loss</code>.
     */
    public Double getProfitLoss() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>test_db.account.last_update</code>.
     */
    public void setLastUpdate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>test_db.account.last_update</code>.
     */
    public LocalDateTime getLastUpdate() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountRecord
     */
    public AccountRecord() {
        super(TBLAccount.ACCOUNT);
    }

    /**
     * Create a detached, initialised AccountRecord
     */
    public AccountRecord(String accountId, String username, Double balance, Double profitLoss, LocalDateTime lastUpdate) {
        super(TBLAccount.ACCOUNT);

        setAccountId(accountId);
        setUsername(username);
        setBalance(balance);
        setProfitLoss(profitLoss);
        setLastUpdate(lastUpdate);
        resetTouchedOnNotNull();
    }
}
