/*
 * This file is generated by jOOQ.
 */
package com.autotesting.db.tables.records;


import com.autotesting.db.tables.TBLTest;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TestRecord extends UpdatableRecordImpl<TestRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>test_db.test.test_id</code>.
     */
    public void setTestId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>test_db.test.test_id</code>.
     */
    public String getTestId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>test_db.test.test_name</code>.
     */
    public void setTestName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>test_db.test.test_name</code>.
     */
    public String getTestName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>test_db.test.counter</code>.
     */
    public void setCounter(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>test_db.test.counter</code>.
     */
    public Integer getCounter() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TestRecord
     */
    public TestRecord() {
        super(TBLTest.TEST);
    }

    /**
     * Create a detached, initialised TestRecord
     */
    public TestRecord(String testId, String testName, Integer counter) {
        super(TBLTest.TEST);

        setTestId(testId);
        setTestName(testName);
        setCounter(counter);
        resetTouchedOnNotNull();
    }
}
