/*
 * This file is generated by jOOQ.
 */
package com.autotesting.db.tables;


import com.autotesting.db.Keys;
import com.autotesting.db.TestDb;
import com.autotesting.db.tables.TBLTrade.TradePath;
import com.autotesting.db.tables.records.AccountRecord;

import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TBLAccount extends TableImpl<AccountRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>test_db.account</code>
     */
    public static final TBLAccount ACCOUNT = new TBLAccount();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AccountRecord> getRecordType() {
        return AccountRecord.class;
    }

    /**
     * The column <code>test_db.account.account_id</code>.
     */
    public final TableField<AccountRecord, String> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.CHAR(36).nullable(false), this, "");

    /**
     * The column <code>test_db.account.username</code>.
     */
    public final TableField<AccountRecord, String> USERNAME = createField(DSL.name("username"), SQLDataType.CHAR(16).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CHAR)), this, "");

    /**
     * The column <code>test_db.account.balance</code>.
     */
    public final TableField<AccountRecord, Double> BALANCE = createField(DSL.name("balance"), SQLDataType.DOUBLE.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.DOUBLE)), this, "");

    /**
     * The column <code>test_db.account.profit_loss</code>.
     */
    public final TableField<AccountRecord, Double> PROFIT_LOSS = createField(DSL.name("profit_loss"), SQLDataType.DOUBLE.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.DOUBLE)), this, "");

    /**
     * The column <code>test_db.account.last_update</code>.
     */
    public final TableField<AccountRecord, LocalDateTime> LAST_UPDATE = createField(DSL.name("last_update"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "");

    private TBLAccount(Name alias, Table<AccountRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TBLAccount(Name alias, Table<AccountRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>test_db.account</code> table reference
     */
    public TBLAccount(String alias) {
        this(DSL.name(alias), ACCOUNT);
    }

    /**
     * Create an aliased <code>test_db.account</code> table reference
     */
    public TBLAccount(Name alias) {
        this(alias, ACCOUNT);
    }

    /**
     * Create a <code>test_db.account</code> table reference
     */
    public TBLAccount() {
        this(DSL.name("account"), null);
    }

    public <O extends Record> TBLAccount(Table<O> path, ForeignKey<O, AccountRecord> childPath, InverseForeignKey<O, AccountRecord> parentPath) {
        super(path, childPath, parentPath, ACCOUNT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AccountPath extends TBLAccount implements Path<AccountRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AccountPath(Table<O> path, ForeignKey<O, AccountRecord> childPath, InverseForeignKey<O, AccountRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AccountPath(Name alias, Table<AccountRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AccountPath as(String alias) {
            return new AccountPath(DSL.name(alias), this);
        }

        @Override
        public AccountPath as(Name alias) {
            return new AccountPath(alias, this);
        }

        @Override
        public AccountPath as(Table<?> alias) {
            return new AccountPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : TestDb.TEST_DB;
    }

    @Override
    public UniqueKey<AccountRecord> getPrimaryKey() {
        return Keys.KEY_ACCOUNT_PRIMARY;
    }

    private transient TradePath _trade;

    /**
     * Get the implicit to-many join path to the <code>test_db.trade</code>
     * table
     */
    public TradePath trade() {
        if (_trade == null)
            _trade = new TradePath(this, null, Keys._1.getInverseKey());

        return _trade;
    }

    @Override
    public TBLAccount as(String alias) {
        return new TBLAccount(DSL.name(alias), this);
    }

    @Override
    public TBLAccount as(Name alias) {
        return new TBLAccount(alias, this);
    }

    @Override
    public TBLAccount as(Table<?> alias) {
        return new TBLAccount(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TBLAccount rename(String name) {
        return new TBLAccount(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TBLAccount rename(Name name) {
        return new TBLAccount(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TBLAccount rename(Table<?> name) {
        return new TBLAccount(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TBLAccount where(Condition condition) {
        return new TBLAccount(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TBLAccount where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TBLAccount where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TBLAccount where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TBLAccount where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TBLAccount where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TBLAccount where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TBLAccount where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TBLAccount whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TBLAccount whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
