/*
 * This file is generated by jOOQ.
 */
package com.autotesting.db.tables;


import com.autotesting.db.Keys;
import com.autotesting.db.TestDb;
import com.autotesting.db.tables.records.TestRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TBLTest extends TableImpl<TestRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>test_db.test</code>
     */
    public static final TBLTest TEST = new TBLTest();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TestRecord> getRecordType() {
        return TestRecord.class;
    }

    /**
     * The column <code>test_db.test.test_id</code>.
     */
    public final TableField<TestRecord, String> TEST_ID = createField(DSL.name("test_id"), SQLDataType.CHAR(36).nullable(false), this, "");

    /**
     * The column <code>test_db.test.test_name</code>.
     */
    public final TableField<TestRecord, String> TEST_NAME = createField(DSL.name("test_name"), SQLDataType.CHAR(32).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CHAR)), this, "");

    /**
     * The column <code>test_db.test.counter</code>.
     */
    public final TableField<TestRecord, Integer> COUNTER = createField(DSL.name("counter"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

    private TBLTest(Name alias, Table<TestRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TBLTest(Name alias, Table<TestRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>test_db.test</code> table reference
     */
    public TBLTest(String alias) {
        this(DSL.name(alias), TEST);
    }

    /**
     * Create an aliased <code>test_db.test</code> table reference
     */
    public TBLTest(Name alias) {
        this(alias, TEST);
    }

    /**
     * Create a <code>test_db.test</code> table reference
     */
    public TBLTest() {
        this(DSL.name("test"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : TestDb.TEST_DB;
    }

    @Override
    public UniqueKey<TestRecord> getPrimaryKey() {
        return Keys.KEY_TEST_PRIMARY;
    }

    @Override
    public TBLTest as(String alias) {
        return new TBLTest(DSL.name(alias), this);
    }

    @Override
    public TBLTest as(Name alias) {
        return new TBLTest(alias, this);
    }

    @Override
    public TBLTest as(Table<?> alias) {
        return new TBLTest(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TBLTest rename(String name) {
        return new TBLTest(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TBLTest rename(Name name) {
        return new TBLTest(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TBLTest rename(Table<?> name) {
        return new TBLTest(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TBLTest where(Condition condition) {
        return new TBLTest(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TBLTest where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TBLTest where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TBLTest where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TBLTest where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TBLTest where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TBLTest where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TBLTest where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TBLTest whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TBLTest whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
