/*
 * This file is generated by jOOQ.
 */
package com.mosson.trade.db.tables.records;


import com.mosson.trade.db.tables.TBLAccount;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AccountRecord extends UpdatableRecordImpl<AccountRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.account.account_id</code>.
     */
    public void setAccountId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.account.account_id</code>.
     */
    public String getAccountId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.account.user_name</code>.
     */
    public void setUserName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.account.user_name</code>.
     */
    public String getUserName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.account.balance</code>.
     */
    public void setBalance(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.account.balance</code>.
     */
    public Double getBalance() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>public.account.profit_loss</code>.
     */
    public void setProfitLoss(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.account.profit_loss</code>.
     */
    public Double getProfitLoss() {
        return (Double) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountRecord
     */
    public AccountRecord() {
        super(TBLAccount.ACCOUNT);
    }

    /**
     * Create a detached, initialised AccountRecord
     */
    public AccountRecord(String accountId, String userName, Double balance, Double profitLoss) {
        super(TBLAccount.ACCOUNT);

        setAccountId(accountId);
        setUserName(userName);
        setBalance(balance);
        setProfitLoss(profitLoss);
        resetTouchedOnNotNull();
    }
}
