/*
 * This file is generated by jOOQ.
 */
package com.mosson.trade.db.tables.records;


import com.mosson.trade.db.tables.TBLTrade;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TradeRecord extends UpdatableRecordImpl<TradeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.trade.trade_id</code>.
     */
    public void setTradeId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.trade.trade_id</code>.
     */
    public String getTradeId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.trade.instrument</code>.
     */
    public void setInstrument(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.trade.instrument</code>.
     */
    public String getInstrument() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.trade.open_price</code>.
     */
    public void setOpenPrice(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.trade.open_price</code>.
     */
    public Double getOpenPrice() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>public.trade.open_time</code>.
     */
    public void setOpenTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.trade.open_time</code>.
     */
    public LocalDateTime getOpenTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.trade.is_open</code>.
     */
    public void setIsOpen(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.trade.is_open</code>.
     */
    public Boolean getIsOpen() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.trade.account_id</code>.
     */
    public void setAccountId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.trade.account_id</code>.
     */
    public String getAccountId() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TradeRecord
     */
    public TradeRecord() {
        super(TBLTrade.TRADE);
    }

    /**
     * Create a detached, initialised TradeRecord
     */
    public TradeRecord(String tradeId, String instrument, Double openPrice, LocalDateTime openTime, Boolean isOpen, String accountId) {
        super(TBLTrade.TRADE);

        setTradeId(tradeId);
        setInstrument(instrument);
        setOpenPrice(openPrice);
        setOpenTime(openTime);
        setIsOpen(isOpen);
        setAccountId(accountId);
        resetTouchedOnNotNull();
    }
}
