/*
 * This file is generated by jOOQ.
 */
package com.mosson.trade.db.routines;


import com.mosson.trade.db.Public;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RTNCloseTrade extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>public.close_trade.trade_to_close_id</code>.
     */
    public static final Parameter<String> TRADE_TO_CLOSE_ID = Internal.createParameter("trade_to_close_id", SQLDataType.CHAR, false, false);

    /**
     * The parameter <code>public.close_trade.closeing_price</code>.
     */
    public static final Parameter<Double> CLOSEING_PRICE = Internal.createParameter("closeing_price", SQLDataType.DOUBLE, false, false);

    /**
     * Create a new routine call instance
     */
    public RTNCloseTrade() {
        super("close_trade", Public.PUBLIC, DSL.comment(""));

        addInParameter(TRADE_TO_CLOSE_ID);
        addInParameter(CLOSEING_PRICE);
        setSQLUsable(false);
    }

    /**
     * Set the <code>trade_to_close_id</code> parameter IN value to the routine
     */
    public void setTradeToCloseId(String value) {
        setValue(TRADE_TO_CLOSE_ID, value);
    }

    /**
     * Set the <code>closeing_price</code> parameter IN value to the routine
     */
    public void setCloseingPrice(Double value) {
        setValue(CLOSEING_PRICE, value);
    }
}
