/*
 * This file is generated by jOOQ.
 */
package com.mosson.trade.db;


import com.mosson.trade.db.tables.TBLAccount;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index TDX_ACCOUNT_USER_NAME = Internal.createIndex(DSL.name("tdx_account_user_name"), TBLAccount.ACCOUNT, new OrderField[] { TBLAccount.ACCOUNT.USER_NAME }, false);
}
