/*
 * This file is generated by jOOQ.
 */
package com.mosson.trade.db;


import com.mosson.trade.db.tables.TBLAccount;
import com.mosson.trade.db.tables.TBLTrade;
import com.mosson.trade.db.tables.records.AccountRecord;
import com.mosson.trade.db.tables.records.TradeRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.QOM.ForeignKeyRule;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccountRecord> ACCOUNT_PKEY = Internal.createUniqueKey(TBLAccount.ACCOUNT, DSL.name("account_pkey"), new TableField[] { TBLAccount.ACCOUNT.ACCOUNT_ID }, true);
    public static final UniqueKey<TradeRecord> TRADE_PKEY = Internal.createUniqueKey(TBLTrade.TRADE, DSL.name("trade_pkey"), new TableField[] { TBLTrade.TRADE.TRADE_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<TradeRecord, AccountRecord> TRADE__TRADE_ACCOUNT_ID_FKEY = Internal.createForeignKey(TBLTrade.TRADE, DSL.name("trade_account_id_fkey"), new TableField[] { TBLTrade.TRADE.ACCOUNT_ID }, Keys.ACCOUNT_PKEY, new TableField[] { TBLAccount.ACCOUNT.ACCOUNT_ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);
}
