/*
 * This file is generated by jOOQ.
 */
package com.mosson.trade.db;


import com.mosson.trade.db.tables.TBLAccount;
import com.mosson.trade.db.tables.TBLTrade;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * standard public schema
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.account</code>.
     */
    public final TBLAccount ACCOUNT = TBLAccount.ACCOUNT;

    /**
     * The table <code>public.trade</code>.
     */
    public final TBLTrade TRADE = TBLTrade.TRADE;

    /**
     * No further instances allowed
     */
    private Public() {
        super(DSL.name("public"), null, DSL.comment("standard public schema"));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            TBLAccount.ACCOUNT,
            TBLTrade.TRADE
        );
    }
}
