/*
 * This file is generated by jOOQ.
 */
package com.mosson.trade.db;


import com.mosson.trade.db.routines.RTNCloseTrade;

import org.jooq.Configuration;


/**
 * Convenience access to all stored procedures and functions in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Routines {

    /**
     * Call <code>public.close_trade</code>
     */
    public static void closeTrade(
          Configuration configuration
        , String tradeToCloseId
        , Double closeingPrice
    ) {
        RTNCloseTrade p = new RTNCloseTrade();
        p.setTradeToCloseId(tradeToCloseId);
        p.setCloseingPrice(closeingPrice);

        p.execute(configuration);
    }
}
