/*
 * This file is generated by jOOQ.
 */
package com.mosson.trade.db;


import com.mosson.trade.db.tables.TBLAccount;
import com.mosson.trade.db.tables.TBLTrade;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.account</code>.
     */
    public static final TBLAccount ACCOUNT = TBLAccount.ACCOUNT;

    /**
     * The table <code>public.trade</code>.
     */
    public static final TBLTrade TRADE = TBLTrade.TRADE;
}
