/*
 * This file is generated by jOOQ.
 */
package com.mosson.trade.db.tables;


import com.mosson.trade.db.Indexes;
import com.mosson.trade.db.Keys;
import com.mosson.trade.db.Public;
import com.mosson.trade.db.tables.TBLTrade.TBLTradePath;
import com.mosson.trade.db.tables.records.AccountRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TBLAccount extends TableImpl<AccountRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.account</code>
     */
    public static final TBLAccount ACCOUNT = new TBLAccount();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AccountRecord> getRecordType() {
        return AccountRecord.class;
    }

    /**
     * The column <code>public.account.account_id</code>.
     */
    public final TableField<AccountRecord, String> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.CHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.account.user_name</code>.
     */
    public final TableField<AccountRecord, String> USER_NAME = createField(DSL.name("user_name"), SQLDataType.CHAR(16), this, "");

    /**
     * The column <code>public.account.balance</code>.
     */
    public final TableField<AccountRecord, Double> BALANCE = createField(DSL.name("balance"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.account.profit_loss</code>.
     */
    public final TableField<AccountRecord, Double> PROFIT_LOSS = createField(DSL.name("profit_loss"), SQLDataType.DOUBLE, this, "");

    private TBLAccount(Name alias, Table<AccountRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TBLAccount(Name alias, Table<AccountRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.account</code> table reference
     */
    public TBLAccount(String alias) {
        this(DSL.name(alias), ACCOUNT);
    }

    /**
     * Create an aliased <code>public.account</code> table reference
     */
    public TBLAccount(Name alias) {
        this(alias, ACCOUNT);
    }

    /**
     * Create a <code>public.account</code> table reference
     */
    public TBLAccount() {
        this(DSL.name("account"), null);
    }

    public <O extends Record> TBLAccount(Table<O> path, ForeignKey<O, AccountRecord> childPath, InverseForeignKey<O, AccountRecord> parentPath) {
        super(path, childPath, parentPath, ACCOUNT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TBLAccountPath extends TBLAccount implements Path<AccountRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TBLAccountPath(Table<O> path, ForeignKey<O, AccountRecord> childPath, InverseForeignKey<O, AccountRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TBLAccountPath(Name alias, Table<AccountRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TBLAccountPath as(String alias) {
            return new TBLAccountPath(DSL.name(alias), this);
        }

        @Override
        public TBLAccountPath as(Name alias) {
            return new TBLAccountPath(alias, this);
        }

        @Override
        public TBLAccountPath as(Table<?> alias) {
            return new TBLAccountPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.TDX_ACCOUNT_USER_NAME);
    }

    @Override
    public UniqueKey<AccountRecord> getPrimaryKey() {
        return Keys.ACCOUNT_PKEY;
    }

    private transient TBLTradePath _trade;

    /**
     * Get the implicit to-many join path to the <code>public.trade</code> table
     */
    public TBLTradePath trade() {
        if (_trade == null)
            _trade = new TBLTradePath(this, null, Keys.TRADE__TRADE_ACCOUNT_ID_FKEY.getInverseKey());

        return _trade;
    }

    @Override
    public TBLAccount as(String alias) {
        return new TBLAccount(DSL.name(alias), this);
    }

    @Override
    public TBLAccount as(Name alias) {
        return new TBLAccount(alias, this);
    }

    @Override
    public TBLAccount as(Table<?> alias) {
        return new TBLAccount(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TBLAccount rename(String name) {
        return new TBLAccount(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TBLAccount rename(Name name) {
        return new TBLAccount(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TBLAccount rename(Table<?> name) {
        return new TBLAccount(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TBLAccount where(Condition condition) {
        return new TBLAccount(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TBLAccount where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TBLAccount where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TBLAccount where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TBLAccount where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TBLAccount where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TBLAccount where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TBLAccount where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TBLAccount whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TBLAccount whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
