/*
 * This file is generated by jOOQ.
 */
package com.mosson.trade.db.tables;


import com.mosson.trade.db.Keys;
import com.mosson.trade.db.Public;
import com.mosson.trade.db.tables.TBLAccount.TBLAccountPath;
import com.mosson.trade.db.tables.records.TradeRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TBLTrade extends TableImpl<TradeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.trade</code>
     */
    public static final TBLTrade TRADE = new TBLTrade();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TradeRecord> getRecordType() {
        return TradeRecord.class;
    }

    /**
     * The column <code>public.trade.trade_id</code>.
     */
    public final TableField<TradeRecord, String> TRADE_ID = createField(DSL.name("trade_id"), SQLDataType.CHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.trade.instrument</code>.
     */
    public final TableField<TradeRecord, String> INSTRUMENT = createField(DSL.name("instrument"), SQLDataType.CHAR(16), this, "");

    /**
     * The column <code>public.trade.open_price</code>.
     */
    public final TableField<TradeRecord, Double> OPEN_PRICE = createField(DSL.name("open_price"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.trade.open_time</code>.
     */
    public final TableField<TradeRecord, LocalDateTime> OPEN_TIME = createField(DSL.name("open_time"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.trade.is_open</code>.
     */
    public final TableField<TradeRecord, Boolean> IS_OPEN = createField(DSL.name("is_open"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.trade.account_id</code>.
     */
    public final TableField<TradeRecord, String> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.CHAR(36), this, "");

    private TBLTrade(Name alias, Table<TradeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TBLTrade(Name alias, Table<TradeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.trade</code> table reference
     */
    public TBLTrade(String alias) {
        this(DSL.name(alias), TRADE);
    }

    /**
     * Create an aliased <code>public.trade</code> table reference
     */
    public TBLTrade(Name alias) {
        this(alias, TRADE);
    }

    /**
     * Create a <code>public.trade</code> table reference
     */
    public TBLTrade() {
        this(DSL.name("trade"), null);
    }

    public <O extends Record> TBLTrade(Table<O> path, ForeignKey<O, TradeRecord> childPath, InverseForeignKey<O, TradeRecord> parentPath) {
        super(path, childPath, parentPath, TRADE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TBLTradePath extends TBLTrade implements Path<TradeRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TBLTradePath(Table<O> path, ForeignKey<O, TradeRecord> childPath, InverseForeignKey<O, TradeRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TBLTradePath(Name alias, Table<TradeRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TBLTradePath as(String alias) {
            return new TBLTradePath(DSL.name(alias), this);
        }

        @Override
        public TBLTradePath as(Name alias) {
            return new TBLTradePath(alias, this);
        }

        @Override
        public TBLTradePath as(Table<?> alias) {
            return new TBLTradePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TradeRecord> getPrimaryKey() {
        return Keys.TRADE_PKEY;
    }

    @Override
    public List<ForeignKey<TradeRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TRADE__TRADE_ACCOUNT_ID_FKEY);
    }

    private transient TBLAccountPath _account;

    /**
     * Get the implicit join path to the <code>public.account</code> table.
     */
    public TBLAccountPath account() {
        if (_account == null)
            _account = new TBLAccountPath(this, Keys.TRADE__TRADE_ACCOUNT_ID_FKEY, null);

        return _account;
    }

    @Override
    public TBLTrade as(String alias) {
        return new TBLTrade(DSL.name(alias), this);
    }

    @Override
    public TBLTrade as(Name alias) {
        return new TBLTrade(alias, this);
    }

    @Override
    public TBLTrade as(Table<?> alias) {
        return new TBLTrade(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TBLTrade rename(String name) {
        return new TBLTrade(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TBLTrade rename(Name name) {
        return new TBLTrade(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TBLTrade rename(Table<?> name) {
        return new TBLTrade(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TBLTrade where(Condition condition) {
        return new TBLTrade(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TBLTrade where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TBLTrade where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TBLTrade where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TBLTrade where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TBLTrade where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TBLTrade where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TBLTrade where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TBLTrade whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TBLTrade whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
