/*
 * This file is generated by jOOQ.
 */
package com.autotesting.db;


import com.autotesting.db.tables.TBLTrade;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in test_db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index TRADE_ACCOUNT_ID = Internal.createIndex(DSL.name("account_id"), TBLTrade.TRADE, new OrderField[] { TBLTrade.TRADE.ACCOUNT_ID }, false);
}
