/*
 * This file is generated by jOOQ.
 */
package com.autotesting.db;


import com.autotesting.db.tables.TBLAccount;
import com.autotesting.db.tables.TBLTest;
import com.autotesting.db.tables.TBLTrade;
import com.autotesting.db.tables.records.AccountRecord;
import com.autotesting.db.tables.records.TestRecord;
import com.autotesting.db.tables.records.TradeRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.QOM.ForeignKeyRule;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * test_db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccountRecord> KEY_ACCOUNT_PRIMARY = Internal.createUniqueKey(TBLAccount.ACCOUNT, DSL.name("KEY_account_PRIMARY"), new TableField[] { TBLAccount.ACCOUNT.ACCOUNT_ID }, true);
    public static final UniqueKey<TestRecord> KEY_TEST_PRIMARY = Internal.createUniqueKey(TBLTest.TEST, DSL.name("KEY_test_PRIMARY"), new TableField[] { TBLTest.TEST.TEST_ID }, true);
    public static final UniqueKey<TradeRecord> KEY_TRADE_PRIMARY = Internal.createUniqueKey(TBLTrade.TRADE, DSL.name("KEY_trade_PRIMARY"), new TableField[] { TBLTrade.TRADE.TRADE_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<TradeRecord, AccountRecord> _1 = Internal.createForeignKey(TBLTrade.TRADE, DSL.name("1"), new TableField[] { TBLTrade.TRADE.ACCOUNT_ID }, Keys.KEY_ACCOUNT_PRIMARY, new TableField[] { TBLAccount.ACCOUNT.ACCOUNT_ID }, true, ForeignKeyRule.RESTRICT, ForeignKeyRule.RESTRICT);
}
