/*
 * This file is generated by jOOQ.
 */
package com.autotesting.db;


import com.autotesting.db.tables.TBLAccount;
import com.autotesting.db.tables.TBLTest;
import com.autotesting.db.tables.TBLTrade;


/**
 * Convenience access to all tables in test_db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>test_db.account</code>.
     */
    public static final TBLAccount ACCOUNT = TBLAccount.ACCOUNT;

    /**
     * The table <code>test_db.test</code>.
     */
    public static final TBLTest TEST = TBLTest.TEST;

    /**
     * The table <code>test_db.trade</code>.
     */
    public static final TBLTrade TRADE = TBLTrade.TRADE;
}
