/*
 * This file is generated by jOOQ.
 */
package com.autotesting.db;


import com.autotesting.db.tables.TBLAccount;
import com.autotesting.db.tables.TBLTest;
import com.autotesting.db.tables.TBLTrade;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TestDb extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>test_db</code>
     */
    public static final TestDb TEST_DB = new TestDb();

    /**
     * The table <code>test_db.account</code>.
     */
    public final TBLAccount ACCOUNT = TBLAccount.ACCOUNT;

    /**
     * The table <code>test_db.test</code>.
     */
    public final TBLTest TEST = TBLTest.TEST;

    /**
     * The table <code>test_db.trade</code>.
     */
    public final TBLTrade TRADE = TBLTrade.TRADE;

    /**
     * No further instances allowed
     */
    private TestDb() {
        super(DSL.name("test_db"), null, DSL.comment(""));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            TBLAccount.ACCOUNT,
            TBLTest.TEST,
            TBLTrade.TRADE
        );
    }
}
